import React from 'react';

const Home = () => {
  return (
    <>
      <div>Hi 1</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
      <div>Hi</div>
      <div>Hiz</div>
    </>
  )
}

export default Home